# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

sudo: required
services:
  - docker

language: R
cache: packages

before_install:
  - "docker pull ubuntu:16.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
